"""create personas, roleplay_sessions, transcript_messages, evaluations

Revision ID: 8dc34c28b7d5
Revises: 
Create Date: 2026-07-25 14:29:11.548119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc34c28b7d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('industry', sa.String(length=120), nullable=False),
    sa.Column('customer_personality', sa.String(length=60), nullable=False),
    sa.Column('company_size', sa.String(length=60), nullable=False),
    sa.Column('decision_maker_role', sa.String(length=120), nullable=False),
    sa.Column('budget', sa.String(length=60), nullable=False),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='persona_difficulty'), nullable=False),
    sa.Column('pain_points', sa.JSON(), nullable=False),
    sa.Column('competitors', sa.JSON(), nullable=False),
    sa.Column('possible_objections', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roleplay_sessions',
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'IN_PROGRESS', 'COMPLETED', name='session_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roleplay_sessions_persona_id'), 'roleplay_sessions', ['persona_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('timeline', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['roleplay_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('transcript_messages',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('speaker', sa.Enum('REP', 'AI_BUYER', name='message_speaker'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['roleplay_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_messages_session_id'), 'transcript_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_messages_session_id'), table_name='transcript_messages')
    op.drop_table('transcript_messages')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_roleplay_sessions_persona_id'), table_name='roleplay_sessions')
    op.drop_table('roleplay_sessions')
    op.drop_table('personas')
    # ### end Alembic commands ###
